
/*
	This file was auto generated by base/build_scripts/make_release.py
	Do not modify unless you know what you're doing.
*/

namespace GameSparks
{
	namespace Core
	{
		// anonymous namespace
		namespace
		{
			static const char GS_VERSION_CODE[] = "0.9.rc4.362";
			static const char GS_RELEASE_DATE[] = "2015-06-16 15:50:20.716537";
			static const char GS_GIT_HASH_SHORT[] = "'9d20ccd";
			static const char GS_GIT_HASH_LONG[] = "9d20ccdd31df42e8b93be80feaae59c01912ae7f'";
		}
	}
}
