
/*
	This file was auto generated by base/build_scripts/make_release.py
	Do not modify unless you know what you're doing.
*/

namespace GameSparks
{
	namespace Core
	{
		// anonymous namespace
		namespace
		{
			static const char GS_VERSION_CODE[] = "0.9.rc4.340";
			static const char GS_RELEASE_DATE[] = "2015-04-22 18:01:47.736636";
			static const char GS_GIT_HASH_SHORT[] = "'3ca888c";
			static const char GS_GIT_HASH_LONG[] = "3ca888c52144513fd89abecac121d33dabeb83d8'";
		}
	}
}
