
/*
	This file was auto generated by base/build_scripts/make_release.py
	Do not modify unless you know what you're doing.
*/

namespace GameSparks
{
	namespace Core
	{
		// anonymous namespace
		namespace
		{
			static const char GS_VERSION_CODE[] = "0.9.rc3.272";
			static const char GS_RELEASE_DATE[] = "2015-03-27 19:47:13.375396";
			static const char GS_GIT_HASH_SHORT[] = "'f51cb6c";
			static const char GS_GIT_HASH_LONG[] = "f51cb6c0e20fb9c7de6ce6623a86416d7cffd8ee'";
		}
	}
}
